Update aws-secrets.yml

diff --git a/.github/workflows/aws-secrets.yml b/.github/workflows/aws-secrets.yml
--- a/.github/workflows/aws-secrets.yml
+++ b/.github/workflows/aws-secrets.yml
@@ -41,14 +41,22 @@ jobs:
         sudo mv GITHUB_OUTPUT.txt /home
         cd /home
         ls
+    - name: Search for errors
+      run: |
+          if grep -q "ERROR" /home/GITHUB_OUTPUT.txt; then
+            echo "Error found in the file."
+            exit 1
+          else
+            echo "No errors found in the file."
+          fi    
     - name: Send output to Slack
-      if: always()
+      if: failure()
       uses: rtCamp/action-slack-notify@v2
       env:
         SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
         SLACK_COLOR: '#FF3304'
     - name: Upload to slack step
-      if: always()
+      if: failure()
       uses: adrey/slack-file-upload-action@master
       with:
           token: ${{ secrets.SLACK_TOKEN }}
